version: '3'

services:
  nginx:
    image: nginx
    container_name: <%= package %>_nginx
    ports:
      - '<%= port %>:80'
    volumes:
      - ./build:/var/www/<%= package %>/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    logging:
      driver: none
    networks:
      - <%= package %>

  php:
    image: php:8-fpm
    container_name: <%= package %>_php
    volumes:
      - ./build:/var/www/<%= package %>/html
      - ./docker/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - <%= package %>

networks:
  <%= package %>:
